# -*- coding: utf-8 -*-
"""kripto_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rvk-Z80xJP8TJVDKkzANOOfUVKeDeC_E
"""

pip install pycryptodome

from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15
from Crypto.Hash import SHA256
import json
from base64 import b64encode, b64decode
from pprint import pprint
import pickle

class ITKoin:
    def generate_rsa_key(self, user_id): # a user_id lesz a filenév töve és két file-t generál: a privát és publikus kulcsoknak
        key = RSA.generate(2048)
        pprint(key)
        publickey = key.publickey()
        pprint(publickey)
        privatekey_filename = user_id + '_priv.pem'
        f = open(privatekey_filename, 'wb')
        f.write(key.export_key())
        f.close()
        publickey_filename = user_id + '_pub.pem'
        f = open(publickey_filename, 'wb')
        f.write(publickey.export_key())
        f.close()
        return

coin=ITKoin()
coin.generate_rsa_key('alma')

