# -*- coding: utf-8 -*-
"""kripto_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kzS4l7Ug2FSnLe1ysGGZ2T8QNyOLH-Wj
"""

pip install pycryptodome

from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15
from Crypto.Hash import SHA256
import json
from base64 import b64encode, b64decode
from pprint import pprint
import pickle

class ITKoin:
    @staticmethod
    def create_hashhexvalue (data):
        pprint(data)
        stringdump = json.dumps(data)
        pprint(stringdump)
        hashobject = SHA256.new(stringdump.encode())
        pprint(hashobject)
        pprint(hashobject.hexdigest())
        return hashobject.hexdigest()

coin=ITKoin()
coin.create_hashhexvalue('XYZ')